import sys
sys.path.insert(0, "../")
import cv2
import base64
from tools.utils import read_file, extract_text_section
from agents.task_agent import TaskAgent


class VideoInterpreter(TaskAgent):
    def __init__(self):
        super().__init__()

        SYSTEM_PROMPT = """
        You are an assistant for generating autonomous vehicle testing scenario. You should generate a detailed description of the road network, the behaviors of the vehicles and the scenario based on the given video data. The input video is framed into a series of images, and each image is generated as a depth map. I will first input a series of images for you and then provide you with all the corresponding depth maps
        Make sure that all of your reasoning is output in the `## Reasoning` section, and in the `## Decision` section you should only output the answers in the given format.
        Your answer should restrictly follow this format:
        ## Description
        Your description of the user request.
        ## Reasoning
        reasoning based on user request, what is the testing goal and what are the best testing scenarios. Try to create complex road network with varying road types, road sturcture and connections.  The generated road network should be *very detailed and shorter than 100m*. Provide detailed description in "road geometry" part in the `## Decision` section.
        ## Decision
        This part should be as detailed as possible. Your output should contain as much concrete data as possible and include the number of the lanes, the width of the lanes, the number of vehicles and so on.
        Important: If you can, plan a route that will reach each point in the network, and describe the road in the first perspective of the agent vehicle.
        Important: If there is a fork in the road, you must point out the angle of the road. And if there is a intersection, you must point out the angle of the intersection.(For example, there is a four-way intersection, you can describe that, the main road points to the north, and the angle between the second road and the main road(the first road) is about 30 degrees, and the angle between the third road and the second road is about 150 degrees, and the third road and the main road is in a straight line and so on.)
        You can also describe angle information like that: "The main road, Pine Street, runs north-south. On the east side, Maple Avenue is located 30 degrees north northeast of the Pine Street, and on the west side, Oak Street is located 45 degrees north northwest of the Pine Street."
        You can identify and analyze the geometric structure of roads by referring to surrounding buildings and trees, as well as cars parked on the roadside and cars walking on the road. You need to give me the position of the surrounding objects relative to the vehicle.  You need to give me the starting position of other vehicles on the lane relative to this vehicle, or the absolute starting position of other vehicles on the lane.
        """

        example_prompt = """
        I give you a example to help you generate better description for road geometry in ##Decision. You should conduct the description like this example.
        ----example begin----
        The road network primarily consists of an intersection where four roads converge. Two of the roads (Road 1 and Road 2) run in the north-south direction and form the main route on which the current vehicle is traveling. Both Road 1 and Road 2 have three lanes for northbound traffic and three lanes for southbound traffic. Road 1 extends northward from the intersection, while Road 2 extends southward from the intersection. Road 3 intersects with Road 1 at a 90-degree angle and extends eastward from the intersection. It has two lanes for eastbound traffic and two lanes for westbound traffic. Road 4 intersects with Road 2 at a 60-degree angle and extends southwestward (i.e., 60 degrees south of east relative to Road 2). It has two lanes for southwestbound traffic and two lanes for traffic in the opposite direction.
        ----example end----
        """

        additional_hints = """
        Use realistic road network descriptions. Typical intersection types include:
        - Crossroad
        - T-intersection
        - Y-intersection
        - Ramp merges
        - Deformed intersections

        Be precise with geometric details, such as:
        - Lane widths (e.g., 3.6 meters standard, turn lanes may be wider).
        - Intersection angles (e.g., 90 degrees, 45 degrees).
        - Road lengths (under 100 meters).
        """

        codeprompt = """
        The following code realize the function of calculate the distance of the vehicle's forward movement.
        The input is the first-person perspective image of the vehicle at the previous and next time points, and the depth map generated by these two images.
        The output is the estimated distance of the vehicle's forward movement.
        The code is as follows:
        ########################################
        import cv2
        import numpy as np
        
        def calculate_distance_from_optical_flow(depth1_path, depth2_path, frame1_path, frame2_path):
            # read and resize two frames
            scale_factor = 0.5
            frame1 = cv2.imread(frame1_path)
            frame2 = cv2.imread(frame2_path)
            frame1 = cv2.resize(frame1, (int(frame1.shape[1] * scale_factor), int(frame1.shape[0] * scale_factor)))
            frame2 = cv2.resize(frame2, (int(frame2.shape[1] * scale_factor), int(frame2.shape[0] * scale_factor)))
            
            # read and resize two depth maps
            depth1 = cv2.imread(depth1_path, cv2.IMREAD_GRAYSCALE)
            depth2 = cv2.imread(depth2_path, cv2.IMREAD_GRAYSCALE)
            depth1 = cv2.resize(depth1, (int(depth1.shape[1] * scale_factor), int(depth1.shape[0] * scale_factor)))
            depth2 = cv2.resize(depth2, (int(depth2.shape[1] * scale_factor), int(depth2.shape[0] * scale_factor)))
            
            if frame1 is None or frame2 is None or depth1 is None or depth2 is None:
                print("cannot read images or depth maps")
                return None
            
            # convert to grayscale
            gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
            gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
        
            # use a region of interest (ROI) to detect feature points
            height, width = gray1.shape
            roi = gray1[int(height * 0.25):int(height * 0.75), int(width * 0.25):int(width * 0.75)]
            
            feature_params = dict(maxCorners=500, qualityLevel=0.3, minDistance=7, blockSize=7)
            p0 = cv2.goodFeaturesToTrack(roi, mask=None, **feature_params)
            p0[:, :, 0] += width * 0.25
            p0[:, :, 1] += height * 0.25
        
            # before calling calcOpticalFlowPyrLK, force gray1 and gray2 to be resized to ensure they are exactly the same
            # resize frame2 and depth2 to the same size as frame1 and depth1
            frame2 = cv2.resize(frame2, (frame1.shape[1], frame1.shape[0]))
            depth2 = cv2.resize(depth2, (depth1.shape[1], depth1.shape[0]))
        
            # convert to grayscale again to ensure the size is the same
            gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
            gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
        
            # before calling calcOpticalFlowPyrLK, force gray1 and gray2 to be resized to ensure they are exactly the same
            assert gray1.shape == gray2.shape, "The shapes of gray1 and gray2 are not equal!"
        
            # use the Lucas-Kanade method to track feature points
            lk_params = dict(winSize=(15, 15), maxLevel=2, criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))
            p1, st, err = cv2.calcOpticalFlowPyrLK(gray1, gray2, p0, None, **lk_params)
        
            # filter out valid optical flow points
            good_new = p1[st == 1]
            good_old = p0[st == 1]
        
            # calculate the depth change for each valid point
            distances = []
            for i, (new, old) in enumerate(zip(good_new, good_old)):
                x_new, y_new = new.ravel()
                x_old, y_old = old.ravel()
        
                # check if the coordinates are within the depth map range
                if (0 <= int(y_old) < depth1.shape[0] and 0 <= int(x_old) < depth1.shape[1] and
                    0 <= int(y_new) < depth2.shape[0] and 0 <= int(x_new) < depth2.shape[1]):
                    # get the depth value at that point in the depth map
                    z1 = depth1[int(y_old), int(x_old)]
                    z2 = depth2[int(y_new), int(x_new)]
        
                    if z1 == 0 or z2 == 0:
                        continue  # skip invalid depth values
        
                    # calculate the depth change
                    depth_change = abs(z2 - z1)
                    distances.append(depth_change)
        
            # calculate the average depth change (roughly estimate the distance the vehicle has moved)
            if distances:
                average_distance = np.mean(distances) / 1000  # convert unit from mm to m
                print(f"Estimated forward distance: {average_distance:.2f} meters")
                return average_distance
            else:
                print("No enough depth data to calculate")
                return None
        
        # input paths
        frame1_path = "1.png"
        frame2_path = "2.png"
        depth1_path = "depth1.png"
        depth2_path = "depth2.png"
        
        # use the function to calculate the distance
        distance = calculate_distance_from_optical_flow(depth1_path, depth2_path, frame1_path, frame2_path)
        
        print("Result:", distance)
        
        ########################################
        You can refer to this code to give the exact distance while giving the vehicle's route.
        """

        # accuracy_prompt_0 = """
        # You need to give me the starting position of the vehicle in the lane.
        # You need to give me the position of the surrounding objects relative to the vehicle.
        # You need to give me the starting position of other vehicles on the lane relative to this vehicle, or the absolute starting position of other vehicles on the lane.
        # If you can, plan a route that will reach each point in the network, and describe the road in the first perspective of the vehicle, which is written in the road description part of ##Decision.
        # If there is a fork in the road, you need to point out the angle of the road.
        # If there is a intersection, you need to point out the angle of the intersection.(For example, there is a four-way intersection, you can describe that, the main road points to the north, and the angle between the second road and the main road(the first road) is about 30 degrees, and the angle between the third road and the second road is about 150 degrees, and the third road and the main road is in a straight line and so on.)
        # You can identify and analyze the geometric structure of roads by referring to surrounding buildings and trees, as well as cars parked on the roadside and cars walking on the road.
        # You can also describe angle information like that: "The main road, Pine Street, runs north-south. On the east side, Maple Avenue is located 30 degrees north northeast of the Pine Street, and on the west side, Oak Street is located 45 degrees north northwest of the Pine Street."
        # """

        # use tuple to prevent modification, this is the fixed part in prompt
        self.pre_prompt = SYSTEM_PROMPT + additional_hints + example_prompt + codeprompt

    def video_encode(self, video, sample_rate=60):
        """Encodes video frames to Base64 format at a given sample rate."""
        base64_frames = []
        cnt = 0
        while video.isOpened():
            if cnt == 0:
                success, frame = video.read()
                if not success:
                    break
                _, buffer = cv2.imencode(".jpg", frame)
                img_base64 = base64.b64encode(buffer).decode("utf-8")
                base64_frames.append(img_base64)
                # here means take one frame every 60 frames(take one frame every 10 seconds)
                cnt = sample_rate
            else:
                cnt -= 1
                success = video.grab()
                if not success:
                    break
        print(f"{len(base64_frames)} frames encoded.")
        return base64_frames

    def refine_request(self, user_request, add_info=None):
        """Refines the user request by incorporating frames and structured prompts."""
        assert "frames" in add_info, "Missing 'frames' key in additional info."
        assert "video_path" in add_info, "Missing 'video_path' key in additional info."
        generation_prompt = self.pre_prompt + f"\nUser request is : {user_request}"
        frames = add_info["frames"]
        sample_rate = add_info.get("frame_sample_rate", 60)
        video = cv2.VideoCapture(add_info["video_path"])

        frames += self.video_encode(video, sample_rate)
        # frames = frames[-1:]
        # print("frames", frames)
        final_request = [
            {"type": "text", "text": generation_prompt},
            *map(
                lambda x: {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{x}"},
                },
                frames,
            ),
        ]
        # print("final_request", final_request)
        return final_request

    def call_agent(self, user_request, added_info):
        answer_not_right = True
        generation_cnt = 0
        output_fn = added_info["output_fn"]
        user_request += """
        I need you to generate a detailed description as much as possible of the road net and the scenario. 
        The description should include all key points (turning points, branching points, intersections) and you must provide detailed distances between the key points. 
        Assuming the speed of the car is 60km/h, you can use this as a reference to estimate the distance.
        You must give me a specific distance value.
        I will give you a list of frames of the video, I need you to generate as many key points as frames for me.
        I only need one description, which includes all the key place points and distances.
        """
        if "frames" not in added_info:
            added_info["frames"] = []

        while answer_not_right:
            self.send_request(user_request, added_info)

            result, answer_not_right = self.extract_decision_data(output_fn)
            generation_cnt += 1
            if generation_cnt > 1:
                print(f"Regenerating scene interpretation! Round:{generation_cnt}")
        return result

    def extract_decision_data(self, file_path):
        """Return extracted structured answer and Need to regenerate or not."""
        text = read_file(file_path)
        decision_text = extract_text_section(text, r"## Decision\n(.+)")

        if decision_text is None:
            return "No decision section found.", True
        return decision_text, False
